### ISSUE TITLE
Error caught was: No module named 'triton'  in windows11

### ISSUE THREAD

**Issue by TomYule** [ClownOfMadness/audiocraft_plus#58]
venv config
```
home = C:\Program Files\Python310
implementation = CPython
version_info = 3.10.0.candidate.2
virtualenv = 20.16.7
include-system-site-packages = false
base-prefix = C:\Program Files\Python310
base-exec-prefix = C:\Program Files\Python310
base-executable = C:\Program Files\Python310\python.exe

```

run app.py  ERROR info
```
E:\AIProject\audiocraft_plus>set TRANSFORMERS_CACHE=.\cache

E:\AIProject\audiocraft_plus>.\venv\Scripts\python.exe .\app.py
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "E:\AIProject\audiocraft_plus\app.py", line 33, in <module>
    from audiocraft.data.audio_utils import convert_audio
  File "E:\AIProject\audiocraft_plus\audiocraft\__init__.py", line 24, in <module>
    from . import data, modules, models
  File "E:\AIProject\audiocraft_plus\audiocraft\data\__init__.py", line 10, in <module>
    from . import audio, audio_dataset, info_audio_dataset, music_dataset, sound_dataset
  File "E:\AIProject\audiocraft_plus\audiocraft\data\info_audio_dataset.py", line 19, in <module>
    from ..modules.conditioners import SegmentWithAttributes, ConditioningAttributes
  File "E:\AIProject\audiocraft_plus\audiocraft\modules\conditioners.py", line 21, in <module>
    import spacy
  File "E:\AIProject\audiocraft_plus\venv\lib\site-packages\spacy\__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "E:\AIProject\audiocraft_plus\venv\lib\site-packages\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "E:\AIProject\audiocraft_plus\venv\lib\site-packages\spacy\pipeline\attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy\pipeline\pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
  File "E:\AIProject\audiocraft_plus\venv\lib\site-packages\spacy\tokens\__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy\tokens\doc.pyx", line 36, in init spacy.tokens.doc
  File "E:\AIProject\audiocraft_plus\venv\lib\site-packages\spacy\schemas.py", line 6, in <module>
    from pydantic import StrictStr, StrictInt, StrictFloat, StrictBool, ConstrainedStr
  File "E:\AIProject\audiocraft_plus\venv\lib\site-packages\pydantic\__init__.py", line 363, in __getattr__
    return _getattr_migration(attr_name)
  File "E:\AIProject\audiocraft_plus\venv\lib\site-packages\pydantic\_migration.py", line 302, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:ConstrainedStr` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.5/u/import-error

E:\AIProject\audiocraft_plus>pause
```

I don't know what to do. Please help me

**Comment by TomYule** [comment]
This setup worked for me

https://github.com/GrandaddyShmax/audiocraft_plus/pull/59

**Comment by keepry** [comment]
**Triton is only supported on Linux**, as mentioned in README.md on GitHub.com/triton-lang/triton. PyPI page has wheels for Python 3.6 - 3.11 on Linux. We don't have any windows CI machine. Just been said as [https://github.com/triton-lang/triton/issues/1057#issuecomment-1500620529](url)

**Comment by rwfsmith** [comment]
can you just install triton-windows?
