### ISSUE TITLE
Sample method error

### ISSUE THREAD

**Issue by alexdoroga** [ClownOfMadness/audiocraft_plus#79]
I'm trying to work through venv because I have a lot of AI working (don't want to break them)

Explain to the newbie why the combination of the finished track does not work (( 
I'll add the settings:
![Screenshot_14](https://github.com/user-attachments/assets/80b74ef7-5fd6-445a-8c00-e78e6ea4b133)
![Screenshot_15](https://github.com/user-attachments/assets/f0ebea9c-e8f3-4184-8b9b-b7c22de7e898)

And the text of the error:

Make a video took 8.46682357788086
video: TFbCaQI8Kh78.mp4
batch finished 1 16.405723810195923
Tempfiles currently stored:  3
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\AI\AudioCraft-plus-portable-win-small-model\miniconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\AI\AudioCraft-plus-portable-win-small-model\miniconda3\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by alexdoroga** [comment]
3,5  minute song too large even for 3090 ))
